# Generated by Django 5.1.5 on 2025-01-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название документа', max_length=256, verbose_name='Название документа')),
                ('file', models.FileField(help_text='Загрузите документ', upload_to='document_files', verbose_name='Документ')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.study', verbose_name='Курс')),
            ],
        ),
    ]
